# Generated by Django 4.0 on 2021-12-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_post_thumbnail_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gh_site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='livesite',
            field=models.URLField(blank=True, null=True),
        ),
    ]
