# Generated by Django 4.0 on 2021-12-31 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_post_gh_site_post_livesite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='gh_site',
            new_name='GitHub',
        ),
    ]
