# Generated by Django 4.0 on 2022-01-01 17:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_gh_site_post_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='GitHub',
            field=models.URLField(default='https://github.com/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='livesite',
            field=models.URLField(default='https://github.com/omololevy'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default='http://res.cloudinary.com/dim8pysls/image/upload/v1639001486/x3mgnqmbi73lten4ewzv.png', max_length=255, null=True, verbose_name='profile_pics/'),
        ),
    ]
