# Generated by Django 4.0 on 2021-12-28 21:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, default='/images/placeholder.png', max_length=255, null=True, verbose_name='project_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default='/user.png', max_length=255, null=True, verbose_name='profile_pics/'),
        ),
    ]
